"""add driver_id to manual bookings

Revision ID: 70146b869cc5
Revises: 143bd7961b17
Create Date: 2026-01-21 10:43:14.519815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70146b869cc5'
down_revision: Union[str, Sequence[str], None] = '143bd7961b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_bookings', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manual_bookings', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manual_bookings', type_='foreignkey')
    op.drop_column('manual_bookings', 'driver_id')
    # ### end Alembic commands ###
