"""add customer table

Revision ID: 75d3997e6cb8
Revises: c95c07e31546
Create Date: 2026-01-23 17:28:07.981754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d3997e6cb8'
down_revision: Union[str, Sequence[str], None] = 'c95c07e31546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_bookings', 'guest_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('manual_bookings', 'country_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'+91'::character varying"))
    op.alter_column('manual_bookings', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_bookings', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('manual_bookings', 'country_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'+91'::character varying"))
    op.alter_column('manual_bookings', 'guest_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
