"""add country code column to manual booking table

Revision ID: 8aeaf85422de
Revises: 70146b869cc5
Create Date: 2026-01-21 18:37:39.289520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aeaf85422de'
down_revision: Union[str, Sequence[str], None] = '70146b869cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('country_code', sa.String(length=10), server_default='+91', nullable=False))
    op.add_column('drivers', sa.Column('country_code', sa.String(length=10), server_default='+91', nullable=False))
    op.add_column('manual_bookings', sa.Column('country_code', sa.String(length=10), server_default='+91', nullable=False))
    op.add_column('tour_packages', sa.Column('currency', sa.String(length=10), server_default='AED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'currency')
    op.drop_column('manual_bookings', 'country_code')
    op.drop_column('drivers', 'country_code')
    op.drop_column('companies', 'country_code')
    # ### end Alembic commands ###
