"""add adults and kids columns to manual_booking

Revision ID: c95c07e31546
Revises: 8aeaf85422de
Create Date: 2026-01-23 10:07:39.684415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95c07e31546'
down_revision: Union[str, Sequence[str], None] = '8aeaf85422de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "manual_bookings",
        sa.Column("adults", sa.Integer(), nullable=False, server_default="1")
    )
    op.add_column(
        "manual_bookings",
        sa.Column("kids", sa.Integer(), nullable=False, server_default="0")
    )

    # remove server default after data is populated
    op.alter_column("manual_bookings", "adults", server_default=None)
    op.alter_column("manual_bookings", "kids", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_bookings', 'kids')
    op.drop_column('manual_bookings', 'adults')
    # ### end Alembic commands ###
