GREETING = "greeting"
CHOOSE_INTENT = "choose_intent"
FAQ = "faq"

TRAVEL_DATE = "travel_date"
PEOPLE_COUNT = "people_count"
BUDGET = "budget"
CITY = "city"
SHOW_PACKAGE = "show_package"
PACKAGE_SELECT = "package_select"
PICKUP = "pickup"
SUMMARY = "summary"
PAYMENT = "payment"
COMPLETED = "completed"
FALLBACK = "fallback"
